
import localFont from 'next/font/local'
import "./globals.css";
import LayoutWrapper from '@/components/Main/LayoutWrapper';
import BackToTop from '@/components/Main/FloatingActions';


const gothic = localFont({
  src: '../../public/assets/fonts/CenturyGothic.ttf',
  display:'swap',
  variable: '--font-gothic'
})
const bigillaBold = localFont({
  src: '../../public/assets/fonts/Bigilla-Bold.otf',
  display:'swap',
  variable: '--font-bigillaBold'
})
const bigilla = localFont({
  src: '../../public/assets/fonts/Bigilla.otf',
  display:'swap',
  variable: '--font-bigilla'
})
const autography = localFont({
  src: '../../public/assets/fonts/Autography.woff',
  display:'swap',
  variable: '--font-autography'
})
const carpethen = localFont({
  src: '../../public/assets/fonts/Carpethen.otf',
  display:'swap',
  variable: '--font-carpethen'
})
const carpethenRegular = localFont({
  src: '../../public/assets/fonts/Carpethen-Regular.woff',
  display:'swap',
  variable: '--font-carpethenRegular'
})

export const metadata = {
  title: "Gulz 🌹",
  description: "Generated by create next app",
  icons:{
   icon:'/assets/images/gulz-icon.png'
  }
};

export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={`${gothic.variable} ${bigillaBold.variable} ${bigilla.variable} ${autography.variable} ${carpethen.variable} ${carpethenRegular.variable} antialiased overflow-x-hidden `}>
        <LayoutWrapper>
        
          {children}
        </LayoutWrapper>
      </body>
    </html>
  );
}
